Fancy indexing

In [4]:
import numpy as np

# Create a matrix of random numbers with 4 rows and 6 columns
first_array = np.random.randint(100, size=(4,6))
print(first_array)
# Index the element on the 3rd row, 2nd col
print(f'The first row in the second column is {first_array[2,1]}')
# Index all of the even rows
#even_array = first_array[first_array % 2 == 0]
sum_rows = first_array.sum(axis=-1)
even_rows = first_array[sum_rows % 2 == 0]

# print(f'The even numbers in the first array are {even_array}')

print(sum_rows)
print(f'The rows in the array that sum up to an even number are  {even_rows}')

# Index all of the elements on even rows and odd columns
sum_col = first_array.sum(axis=0)
odd_col = first_array[:,sum_col % 2 != 0]
print(sum_col)
print(f'The columns in the array that sum up to an odds number are  {odd_col}')
try:
    even_row_and_odd_col = first_array[sum_rows % 2 == 0, sum_col % 2 != 0]
    print(f'The data with odd cols and even rows only are {even_row_and_odd_col}')
except:
    print(f'There is no part of the array with even rows and odd columns')

# Index the elements along the diagonal
diag_index = np.diagonal(first_array)
print(f'The diagnoal index is {diag_index}')

[[94 72 85 76 71 81]
 [78 83 10 41 82 82]
 [92 56 49 21 57 42]
 [49 62 10  3 24 45]]
The first row in the second column is 56
[479 376 317 193]
The rows in the array that sum up to an even number are  [[78 83 10 41 82 82]]
[313 273 154 141 234 250]
The columns in the array that sum up to an odds number are  [[94 72 76]
 [78 83 41]
 [92 56 21]
 [49 62  3]]
The data with odd cols and even rows only are [78 83 41]
The diagnoal index is [94 83 49  3]


Broadcasting

In [80]:
import random
# Create a random matrix of binary values (0, 1)
second_array = np.random.randint(2, size=(random.randint(1,5),random.randint(1,5)))
print(second_array)
# Create a vector with as many rows as the matrix containing random positive integers between 1 and 5
rows, colunms = np.shape(second_array)
vector = np.random.randint(6,size=rows).reshape(rows,1) # This doesnt work because it reshapes
print(vector)
# Add the vector to every column using broadcasting
second_array + vector
print(second_array)
# Create a new matrix by multiplying the columns of the original by the vector
new_matrix = second_array * vector
print(new_matrix)
# Create a new matrix by multiplying every element by a scalar value
matrix_scalar = second_array * 2
print(matrix_scalar)

[[1]
 [0]
 [1]]
[[3]
 [0]
 [4]]
[[1]
 [0]
 [1]]
[[3]
 [0]
 [4]]
[[2]
 [0]
 [2]]


Bordering an array

In [187]:
# Write a NumPy program to add a border of zeros to the outside elements of an array of size (20, 20).
np.random.seed(2)
# a = np.random.randint(10, size=(5,5))
# b = np.pad(a, pad_width=1, mode='constant', constant_values=0)
# print(b)
# Can you do it with an 3D array of dimension (20, 20, 20)?
# c = np.random.randint(10, size=(2,2,2))
# d = np.pad(c, pad_width=1, mode='constant', constant_values=0)
# print(d)
# Try the same with an array of dimension (20, 40, 10)

e = np.random.randint(10, size=(2,4,2))
f = np.pad(c, pad_width=1, mode='constant', constant_values=0)
print(e)
print(f)

[[[8 8]
  [6 2]
  [8 7]
  [2 1]]

 [[5 4]
  [4 5]
  [7 3]
  [6 4]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 8 8 0]
  [0 6 2 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 8 7 0]
  [0 2 1 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


Checkerboard arrays

In [224]:
# Create a numpy array of dimension (20, 20) and fill it with a checkerboard pattern of 1's and 0's.
checkerboard = np.zeros((20,20))
checkerboard[1::2,::2] = 1 # 1::2 is second row plus every 2 rows - then the bit after the "," is the first row plus every 2 and the second colunm plus every 2
checkerboard[::2, 1::2] = 1 
# Can you do the same for a 3D array of dimension (20, 20, 20)
checkboard_3d =np.zeros((4,4,4))
checkboard_3d[::1,1::2,::2] = 1 
checkboard_3d[::1,::2, 1::2] = 1 
# print(checkboard_3d)
# What about an array of dimension (20, 40, 10)
checkboard_3d_rect =np.zeros((10,20,5))
checkboard_3d_rect[::1,1::2,::2] = 1 
# checkboard_3d[::1,::2, 1::2] = 1
# checkboard_3d[::1,::2, 1::2] = 1
print(checkboard_3d_rect)



[[[0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]]

 [[0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]]

 [[0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [0. 0.

Count the unique values in a row

In [255]:
# Create a numpy array
np.random.seed(2)
arr = np.random.randint(0,10,size=(2, 3))
print(arr)
# Compute the count of unique values in each row.
# unique, counts = np.unique(arr, return_counts=True)
# unique_count = np.column_stack((unique, counts))
# print(unique_count)
np.unique(arr, axis=0, return_counts=True)



[[8 8 6]
 [2 8 7]]


(array([[2, 8, 7],
        [8, 8, 6]]),
 array([1, 1]))

Quiz playground

In [262]:
x = np.array([[1],[2],[3]]) * np.array([[1,2]])
np.shape(x)


(3, 2)

In [266]:
np.eye(1)

array([[1.]])