Fancy indexing

In [44]:
import numpy as np

# Create a matrix of random numbers with 4 rows and 6 columns
first_array = np.random.randint(100, size=(4,6))
print(first_array)
# Index the element on the 3rd row, 2nd col
print(f'The first row in the second column is {first_array[2,1]}')
# Index all of the even rows
#even_array = first_array[first_array % 2 == 0]
sum_rows = first_array.sum(axis=-1)
even_rows = first_array[sum_rows % 2 == 0]

# print(f'The even numbers in the first array are {even_array}')

print(sum_rows)
print(f'The rows in the array that sum up to an even number are  {even_rows}')

# Index all of the elements on even rows and odd columns
sum_col = first_array.sum(axis=0)
odd_col = first_array[:,sum_col % 2 != 0]
print(sum_col)
print(f'The columns in the array that sum up to an odds number are  {odd_col}')
try:
    even_row_and_odd_col = first_array[sum_rows % 2 == 0, sum_col % 2 != 0]
    print(f'The data with odd cols and even rows only are {even_row_and_odd_col}')
except:
    print(f'There is no part of the array with even rows and odd columns')

# Index the elements along the diagonal
diag_index = np.diagonal(first_array)
print(f'The diagnoal index is {diag_index}')

[[ 1 70 77 61 86 69]
 [ 2 68 63 98 45  0]
 [10 75 95  1 86 90]
 [98 57 40 62 38 48]]
The first row in the second column is 75
[364 276 357 343]
The rows in the array that sum up to an even number are  [[ 1 70 77 61 86 69]
 [ 2 68 63 98 45  0]]
[111 270 275 222 255 207]
The columns in the array that sum up to an odds number are  [[ 1 77 86 69]
 [ 2 63 45  0]
 [10 95 86 90]
 [98 40 38 48]]
There is no part of the array with even rows and odd columns
The diagnoal index is [ 1 68 95 62]


Broadcasting

In [71]:
import random
# Create a random matrix of binary values (0, 1)
second_array = np.random.randint(2, size=(random.randint(1,20),random.randint(1,20)))
print(second_array)
# Create a vector with as many rows as the matrix containing random positive integers between 1 and 5
rows, colunms = np.shape(second_array)
print(np.shape(second_array))
print(rows)
print(colunms)
np.random.randint(6,size=rows).reshape(-1,rows)
# Add the vector to every column using broadcasting
# Create a new matrix by multiplying the columns of the original by the vector
# Create a new matrix by multiplying every element by a scalar value

[[0 0 1 0 0]
 [1 0 1 1 1]
 [0 1 0 0 0]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [0 0 1 1 1]
 [0 0 1 0 1]
 [1 1 0 0 1]
 [0 0 1 0 1]
 [0 1 1 1 0]
 [1 0 0 1 1]
 [1 1 0 0 0]
 [0 1 0 0 1]
 [1 1 0 0 1]
 [1 1 0 1 1]
 [0 1 1 0 0]]
(16, 5)
16
5


array([[2, 0, 3, 5, 0, 4, 3, 0, 2, 3, 4, 0, 4, 4, 2, 1]])