Fancy indexing

In [4]:
import numpy as np

# Create a matrix of random numbers with 4 rows and 6 columns
first_array = np.random.randint(100, size=(4,6))
print(first_array)
# Index the element on the 3rd row, 2nd col
print(f'The first row in the second column is {first_array[2,1]}')
# Index all of the even rows
#even_array = first_array[first_array % 2 == 0]
sum_rows = first_array.sum(axis=-1)
even_rows = first_array[sum_rows % 2 == 0]

# print(f'The even numbers in the first array are {even_array}')

print(sum_rows)
print(f'The rows in the array that sum up to an even number are  {even_rows}')

# Index all of the elements on even rows and odd columns
sum_col = first_array.sum(axis=0)
odd_col = first_array[:,sum_col % 2 != 0]
print(sum_col)
print(f'The columns in the array that sum up to an odds number are  {odd_col}')
try:
    even_row_and_odd_col = first_array[sum_rows % 2 == 0, sum_col % 2 != 0]
    print(f'The data with odd cols and even rows only are {even_row_and_odd_col}')
except:
    print(f'There is no part of the array with even rows and odd columns')

# Index the elements along the diagonal
diag_index = np.diagonal(first_array)
print(f'The diagnoal index is {diag_index}')

[[94 72 85 76 71 81]
 [78 83 10 41 82 82]
 [92 56 49 21 57 42]
 [49 62 10  3 24 45]]
The first row in the second column is 56
[479 376 317 193]
The rows in the array that sum up to an even number are  [[78 83 10 41 82 82]]
[313 273 154 141 234 250]
The columns in the array that sum up to an odds number are  [[94 72 76]
 [78 83 41]
 [92 56 21]
 [49 62  3]]
The data with odd cols and even rows only are [78 83 41]
The diagnoal index is [94 83 49  3]


Broadcasting

In [80]:
import random
# Create a random matrix of binary values (0, 1)
second_array = np.random.randint(2, size=(random.randint(1,5),random.randint(1,5)))
print(second_array)
# Create a vector with as many rows as the matrix containing random positive integers between 1 and 5
rows, colunms = np.shape(second_array)
vector = np.random.randint(6,size=rows).reshape(rows,1) # This doesnt work because it reshapes
print(vector)
# Add the vector to every column using broadcasting
second_array + vector
print(second_array)
# Create a new matrix by multiplying the columns of the original by the vector
new_matrix = second_array * vector
print(new_matrix)
# Create a new matrix by multiplying every element by a scalar value
matrix_scalar = second_array * 2
print(matrix_scalar)

[[1]
 [0]
 [1]]
[[3]
 [0]
 [4]]
[[1]
 [0]
 [1]]
[[3]
 [0]
 [4]]
[[2]
 [0]
 [2]]
